//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Docente.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOLSA_TRABAJO
    {
        public int id_Bolsa { get; set; }
        public string EnteEncargado { get; set; }
        public string PortalWebBolsa { get; set; }
        public int id_Documento { get; set; }
        public string NombreBolsa { get; set; }
    
        public virtual Documento_Bolsa Documento_Bolsa { get; set; }
    }
}
