//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Docente.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Categoria_Docentes
    {
        public int id_Categoria { get; set; }
        public int id_Docente { get; set; }
        public string ObservacionesCat { get; set; }
    
        public virtual Categoria Categoria { get; set; }
    }
}
