//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Docente.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CONCYTECEntities : DbContext
    {
        public CONCYTECEntities()
            : base("name=CONCYTECEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DOCENTES_CONCYTEC> DOCENTES_CONCYTEC { get; set; }
        public virtual DbSet<Experiencia> Experiencia { get; set; }
        public virtual DbSet<ExperienciaXDocente> ExperienciaXDocente { get; set; }
        public virtual DbSet<Tipo_DocConcytec> Tipo_DocConcytec { get; set; }
    }
}
