//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Docente.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOCENTES_CONCYTEC
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DOCENTES_CONCYTEC()
        {
            this.ExperienciaXDocente = new HashSet<ExperienciaXDocente>();
        }
    
        public int id_DocConcytec { get; set; }
        public string Nombres { get; set; }
        public string ApellidoPaterno { get; set; }
        public string ApellidoMaterno { get; set; }
        public string Nacionalidad { get; set; }
        public string DNI_Carnet { get; set; }
        public int id_TipDocCon { get; set; }
    
        public virtual Tipo_DocConcytec Tipo_DocConcytec { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExperienciaXDocente> ExperienciaXDocente { get; set; }
    }
}
