//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Docente.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOCENTE
    {
        public int id_Docente { get; set; }
        public string Nombres { get; set; }
        public string Apellido_Paterno { get; set; }
        public Nullable<System.DateTime> Fecha_Nacimiento { get; set; }
        public string Apellido_Materno { get; set; }
        public string Nacionalidad { get; set; }
        public string DNI_CarnetExtranjeria { get; set; }
        public string TiempoDocencia { get; set; }
        public int id_TipDocente { get; set; }
        public int id_Documento { get; set; }
    
        public virtual Documentos_Docente Documentos_Docente { get; set; }
        public virtual Tipo_Docente Tipo_Docente { get; set; }
    }
}
