//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Docente.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExperienciaXDocente
    {
        public int id_DocConcytec { get; set; }
        public int id_Experiencia { get; set; }
        public string Experiencia1 { get; set; }
        public string Experiencia2 { get; set; }
        public string Experiencia3 { get; set; }
        public string Experiencia4 { get; set; }
    
        public virtual DOCENTES_CONCYTEC DOCENTES_CONCYTEC { get; set; }
        public virtual Experiencia Experiencia { get; set; }
    }
}
