//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Docente.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExperienciaXDocente
    {
        public int id_DocConcytec { get; set; }
        public int id_Experiencia { get; set; }
        public string Experiencia1 { get; set; }
        public string Experiencia2 { get; set; }
        public string Experiencia3 { get; set; }
        public string Experiencia4 { get; set; }
    
        public virtual DOCENTES_CONCYTEC DOCENTES_CONCYTEC { get; set; }
        public virtual Experiencia Experiencia { get; set; }
    }
}
