//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Docente.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INVESTIGACION
    {
        public int id_Investigación { get; set; }
        public string DescripcionInv { get; set; }
        public int Id_Proyecto { get; set; }
        public int id_Documento { get; set; }
    
        public virtual Documentos_Investigacion Documentos_Investigacion { get; set; }
        public virtual Proyectos Proyectos { get; set; }
    }
}
