//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Docente.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProgramasXCarrera
    {
        public int id_Carrera { get; set; }
        public int id_Programa { get; set; }
        public Nullable<System.DateTime> FechaInicio { get; set; }
        public int id_Docente { get; set; }
    
        public virtual Carrera Carrera { get; set; }
    }
}
