//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Docente.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEDE
    {
        public int id_Sede { get; set; }
        public int id_SedeCentral { get; set; }
        public int id_localidad { get; set; }
        public string NombreSede { get; set; }
        public string CantidadLaboratorios { get; set; }
        public string CantidadTalleres { get; set; }
        public string CantidadAmbientesParaDocentes { get; set; }
        public string CantidadAulas { get; set; }
        public string CantidadBibliotecas { get; set; }
        public string CantidadAuditorio { get; set; }
        public string CantidadCanchasDeportivas { get; set; }
        public string CantidadSalasEstudio { get; set; }
        public string CantidadSalasInvest { get; set; }
        public string CantidadAcervoBibliog { get; set; }
        public string Jerarquia { get; set; }
        public Nullable<System.DateTime> FechaPrimerPA { get; set; }
        public string CantidadEstudiantes { get; set; }
        public string NombreFacultad { get; set; }
        public string NumeroLocal { get; set; }
        public string CodigoLocal { get; set; }
    
        public virtual Localidad Localidad { get; set; }
    }
}
