//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Docente.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SERVICIOS_COMPLEMENTARIOS
    {
        public int id_Servicios { get; set; }
        public string DescripcionServicio { get; set; }
        public string NumeroDeServicios { get; set; }
        public int id_Documento { get; set; }
    
        public virtual Documento_Servicio Documento_Servicio { get; set; }
    }
}
