//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Docente.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SUNEDU : DbContext
    {
        public SUNEDU()
            : base("name=SUNEDU")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ACCESO> ACCESO { get; set; }
        public virtual DbSet<Autorizacion> Autorizacion { get; set; }
        public virtual DbSet<BOLSA_TRABAJO> BOLSA_TRABAJO { get; set; }
        public virtual DbSet<Carrera> Carrera { get; set; }
        public virtual DbSet<Categoria> Categoria { get; set; }
        public virtual DbSet<Categoria_Docentes> Categoria_Docentes { get; set; }
        public virtual DbSet<CategoriaXCarrera> CategoriaXCarrera { get; set; }
        public virtual DbSet<DOCENTE> DOCENTE { get; set; }
        public virtual DbSet<DocenteXSede> DocenteXSede { get; set; }
        public virtual DbSet<Documento_Bolsa> Documento_Bolsa { get; set; }
        public virtual DbSet<Documento_Servicio> Documento_Servicio { get; set; }
        public virtual DbSet<Documento_Transparencia> Documento_Transparencia { get; set; }
        public virtual DbSet<Documentos_Docente> Documentos_Docente { get; set; }
        public virtual DbSet<Documentos_Investigacion> Documentos_Investigacion { get; set; }
        public virtual DbSet<Documentos_Universidad> Documentos_Universidad { get; set; }
        public virtual DbSet<FINANZAS> FINANZAS { get; set; }
        public virtual DbSet<Grado> Grado { get; set; }
        public virtual DbSet<Grado_Docente> Grado_Docente { get; set; }
        public virtual DbSet<INVESTIGACION> INVESTIGACION { get; set; }
        public virtual DbSet<InvestigacionXDocente> InvestigacionXDocente { get; set; }
        public virtual DbSet<Localidad> Localidad { get; set; }
        public virtual DbSet<Modalidad_Creacion> Modalidad_Creacion { get; set; }
        public virtual DbSet<Periodo_Academico> Periodo_Academico { get; set; }
        public virtual DbSet<PROGRAMA> PROGRAMA { get; set; }
        public virtual DbSet<ProgramasXCarrera> ProgramasXCarrera { get; set; }
        public virtual DbSet<ProgramaXSede> ProgramaXSede { get; set; }
        public virtual DbSet<Proyectos> Proyectos { get; set; }
        public virtual DbSet<SEDE> SEDE { get; set; }
        public virtual DbSet<SERVICIOS_COMPLEMENTARIOS> SERVICIOS_COMPLEMENTARIOS { get; set; }
        public virtual DbSet<Tip_Grado> Tip_Grado { get; set; }
        public virtual DbSet<Tipo_Categoria> Tipo_Categoria { get; set; }
        public virtual DbSet<Tipo_Docente> Tipo_Docente { get; set; }
        public virtual DbSet<TipoGestion> TipoGestion { get; set; }
        public virtual DbSet<TRANSPARENCIA> TRANSPARENCIA { get; set; }
        public virtual DbSet<UNIVERSIDAD> UNIVERSIDAD { get; set; }
    }
}
