//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Docente.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tipo_DocConcytec
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tipo_DocConcytec()
        {
            this.DOCENTES_CONCYTEC = new HashSet<DOCENTES_CONCYTEC>();
        }
    
        public int id_TipDocCon { get; set; }
        public string DescripcionTipCon { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DOCENTES_CONCYTEC> DOCENTES_CONCYTEC { get; set; }
    }
}
