//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Docente.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRANSPARENCIA
    {
        public int id_Transparencia { get; set; }
        public string PortalWeb { get; set; }
        public string Mision { get; set; }
        public string Vision { get; set; }
        public int id_Documento { get; set; }
    
        public virtual Documento_Transparencia Documento_Transparencia { get; set; }
    }
}
