//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Docente.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UNIVERSIDAD
    {
        public int id_Universidad { get; set; }
        public string id_Acceso { get; set; }
        public int id_Investigación { get; set; }
        public int id_Docente { get; set; }
        public int id_Programa { get; set; }
        public string Nombre { get; set; }
        public string NRuc { get; set; }
        public string RazonSocial { get; set; }
        public int id_Documento { get; set; }
        public int id_Autorizacion { get; set; }
        public int id_Gestion { get; set; }
        public int id_ModCreacion { get; set; }
        public int id_Sede { get; set; }
        public int id_Servicios { get; set; }
        public int id_Bolsa { get; set; }
        public int id_Transparencia { get; set; }
        public int id_Finanzas { get; set; }
    
        public virtual ACCESO ACCESO { get; set; }
        public virtual Autorizacion Autorizacion { get; set; }
        public virtual Documentos_Universidad Documentos_Universidad { get; set; }
        public virtual FINANZAS FINANZAS { get; set; }
        public virtual Modalidad_Creacion Modalidad_Creacion { get; set; }
        public virtual TipoGestion TipoGestion { get; set; }
    }
}
